#.travis.yml
 
dist: trusty

sudo: required

language: node_js

node_js:
  - 12.4.0

branches:
  only:
    - master

git:
  depth: false

addons:
  chrome: stable

before_script:
  - set -e
  - npm install
  - npm run build:library
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox  

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build:ssr:prod
  - sonar-scanner

notifications:
  email:
    on_failure: change
    on_success: change