language: node_js
node_js:
  - "9"
dist: trusty
sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cliscript:
- ng lint
- ng build --prod --base-href https://github.com/achachia/crowdlending-front-end.git